sched: Introduce BORE Scheduler
constgran vanilla-max
sched: Make latency / granularity constant
tunable_scaling = 1 (logarithmic) -> 0 (constant)
latency_ns = variable 6-24ms -> constant 24ms
min_granularity_ns = variable 0.75-3ms -> constant 3ms
wakeup_granularity_ns = variable 1-4ms -> constant 4ms

5.15.y-bore3.1.2

fixed: fair.c

fixed: fork.c, core.c

fix: error: implicit declaration of function 'sched_post_fork'

fix: error: use of undeclared identifier 'SYSCTL_ZERO'

fix: compile switch CONFIG_SCHED_BORE would make compile fail on fair.c:calc_delta_fair_half

fork_burst_penalty: thread-fork traverse through threads in same process
added: sched_bore_extra_flags (default: 0) for performance experiments
&0x1: START_DEBIT effect scaled by full burst-score instead of half

version number 3.1.2 -> 3.1.4

sched_bore_extra_flags &0x2: Forked thread inherits average burst score of thread group

version number 3.1.4 -> 3.1.5

Deleted: sched_bore_extra_flags
sched_bore_extra_flags &0x2 moved to sched_burst_fork_atavistic &0x4

Do not use DIV_ROUND_CLOSEST in average inheritance calculation

Renamed: penalty_scale -> penalty_scale_mayhalve

Renamed: calc_delta_fair_debit -> calc_delta_fair_enq

version number 3.1.5 -> 3.1.8

bore-scheduler: Fix compile